### ISSUE TITLE
CollisionCheck class in simObject.py

### ISSUE THREAD

**Issue by poliandre98** [nndei/dVRL_Neri#2]
Hi @nndei, I'm trying to define my own collisionCheck class in order to manage the collision in the simulation. 
![collisionCheck](https://user-images.githubusercontent.com/75742998/102556497-4e3a9b80-40c9-11eb-9a67-f315c9644f08.png)
However during the training with baselines/her algorithm this error occurs: 
![error](https://user-images.githubusercontent.com/75742998/102556750-e3d62b00-40c9-11eb-9d07-f4db9388bfdd.png)
despite the object 'L3_sx_respondable_TOOL1', 'L3_dx_respondable_TOOL1' and 'L1_respondable_TOOL1' are all defined in V-REP scene. 

I've seen that also in your code in simObject.py is implemented the collisionCheck class, however I didn't get to what scene objects the string inside getCollisionHandle refers to 
![collisionCheck2](https://user-images.githubusercontent.com/75742998/102556976-770f6080-40ca-11eb-8cfc-0faee8dc9192.png)
I didn't find any of the objects that you have defined in getCollisionHandle in your dVRK-oneArm-pick and dVRK-oneArm-pick_res V-REP scenes.

Can you help me in understand how to manage the object to pass in getCollisionHandle? 

Thank you, Best Regards. 
Andrea.

**Comment by nndei** [comment]
Dear Andrea,

The function getCollisionHandle, as indicated by CoppeliaSim, gets the handle of a **collision object**. You are passing scene objects instead. 

See: https://www.coppeliarobotics.com/helpFiles/en/regularApi/simGetCollisionHandle.htm

In order to check the collision state of an object like  'L3_sx_respondable_TOOL1', you first need to define in CoppeliaSim a corresponding collision object. 
By following this guide https://www.coppeliarobotics.com/helpFiles/en/collisionDetection.htm you will see that all my collision objects you cannot find in the scene are actually in there, but you won't find them in the hierarchy tree on the left, rather in the collision detection dialog.

Regards,
Neri

**Comment by nndei** [comment]
Side note: before starting the training, it is mandatory to check if things work using an external script. That is the purpose of reach_control.py and pick_control.py (in the respective folders). When executed, the files open a Docker container of the specific image and you can check how the system performs (if the image is mounted without the -h flag in the Dockerfile).

Without that, you are going to run a very long training without being sure you're working with something that actually does what it was meant to do.

Regards,
Neri

**Comment by poliandre98** [comment]
> Hi @nndei, I'm trying to define my own collisionCheck class in order to manage the collision in the simulation.
> ![collisionCheck](https://user-images.githubusercontent.com/75742998/102556497-4e3a9b80-40c9-11eb-9a67-f315c9644f08.png)
> However during the training with baselines/her algorithm this error occurs:
> ![error](https://user-images.githubusercontent.com/75742998/102556750-e3d62b00-40c9-11eb-9d07-f4db9388bfdd.png)
> despite the object 'L3_sx_respondable_TOOL1', 'L3_dx_respondable_TOOL1' and 'L1_respondable_TOOL1' are all defined in V-REP scene.
> 
> I've seen that also in your code in simObject.py is implemented the collisionCheck class, however I didn't get to what scene objects the string inside getCollisionHandle refers to
> ![collisionCheck2](https://user-images.githubusercontent.com/75742998/102556976-770f6080-40ca-11eb-8cfc-0faee8dc9192.png)
> I didn't find any of the objects that you have defined in getCollisionHandle in your dVRK-oneArm-pick and dVRK-oneArm-pick_res V-REP scenes.
> 
> Can you help me in understand how to manage the object to pass in getCollisionHandle?
> 
> Thank you, Best Regards.
> Andrea.

Hi @nndei I have just found the 

> Dear Andrea,
> 
> The function getCollisionHandle, as indicated by CoppeliaSim, gets the handle of a **collision object**. You are passing scene objects instead.
> 
> See: https://www.coppeliarobotics.com/helpFiles/en/regularApi/simGetCollisionHandle.htm
> 
> In order to check the collision state of an object like 'L3_sx_respondable_TOOL1', you first need to define in CoppeliaSim a corresponding collision object.
> By following this guide https://www.coppeliarobotics.com/helpFiles/en/collisionDetection.htm you will see that all my collision objects you cannot find in the scene are actually in there, but you won't find them in the hierarchy tree on the left, rather in the collision detection dialog.
> 
> Regards,
> Neri

@nndei Thank you very much. I've created my collision Handle in V-REP following your instruction and the error in the training doesn't occur anymore. 
Thanks very much also for the Side Note: I will follow your advice for future trainings

Regards, 
Andrea

**Comment by nndei** [comment]
Hi, that's great! Yeah, try things out beforehand. Training is the easiest part!
