### ISSUE TITLE
Failed in V-REP connection 

### ISSUE THREAD

**Issue by poliandre98** [nndei/dVRL_Neri#3]
> Hi @nndei, I'm trying to define my own collisionCheck class in order to manage the collision in the simulation.
> ![collisionCheck](https://user-images.githubusercontent.com/75742998/102556497-4e3a9b80-40c9-11eb-9a67-f315c9644f08.png)
> However during the training with baselines/her algorithm this error occurs:
> ![error](https://user-images.githubusercontent.com/75742998/102556750-e3d62b00-40c9-11eb-9d07-f4db9388bfdd.png)
> despite the object 'L3_sx_respondable_TOOL1', 'L3_dx_respondable_TOOL1' and 'L1_respondable_TOOL1' are all defined in V-REP scene.
> 
> I've seen that also in your code in simObject.py is implemented the collisionCheck class, however I didn't get to what scene objects the string inside getCollisionHandle refers to
> ![collisionCheck2](https://user-images.githubusercontent.com/75742998/102556976-770f6080-40ca-11eb-8cfc-0faee8dc9192.png)
> I didn't find any of the objects that you have defined in getCollisionHandle in your dVRK-oneArm-pick and dVRK-oneArm-pick_res V-REP scenes.
> 
> Can you help me in understand how to manage the object to pass in getCollisionHandle?
> 
> Thank you, Best Regards.
> Andrea.

Hi @nndei I have just found the 

> Dear Andrea,
> 
> The function getCollisionHandle, as indicated by CoppeliaSim, gets the handle of a **collision object**. You are passing scene objects instead.
> 
> See: https://www.coppeliarobotics.com/helpFiles/en/regularApi/simGetCollisionHandle.htm
> 
> In order to check the collision state of an object like 'L3_sx_respondable_TOOL1', you first need to define in CoppeliaSim a corresponding collision object.
> By following this guide https://www.coppeliarobotics.com/helpFiles/en/collisionDetection.htm you will see that all my collision objects you cannot find in the scene are actually in there, but you won't find them in the hierarchy tree on the left, rather in the collision detection dialog.
> 
> Regards,
> Neri

@nndei Thank you very much. I've created my collision Handle in V-REP following your instruction and the error in the training doesn't occur anymore. 
Thanks very much also for the Side Note: I will follow your advice for future trainings

Regards, 
Andrea

_Originally posted by @poliandre98 in https://github.com/nndei/dVRL_Neri/issues/2#issuecomment-748162009_

**Comment by poliandre98** [comment]
Hi @nndei, I've created the Handle collision as you suggested. However it seems that the V-REP opening with the handle of a collision object requires so many times and causes the failure of connection when I try to start the training (or when I perform the check before the training using external script).
Do you think that these events are caused by the usage of a non-pure shapes as obstacles in the V-REP scene? 

Thank you. 
Best Regards, Andrea.

**Comment by nndei** [comment]
Hello @poliandre98, please reopen a closed issue next time for context.

I really can’t help. I suggest you try out with simple shapes first and see. I only employed a simple shape, the cuboid, and I suggest doing so as well.

**Comment by poliandre98** [comment]
Hi @nndei, it seems that the problem iwas caused by the randomization of the target position between 6 choices, as using a fixed target (or a uniformly sampled target in a region of the scene) solved the problem. I don't know the reason why of that. Moreover for the target randomization between 6 choices I've seen your simObject.py code and in particular the targetK class, trying to replicate for my purpose. Have you ever had a problem like this in your experience?
Thanks so much for the help, Best Regards. 
Andrea.

**Comment by nndei** [comment]
Dear @poliandre98, I have not fully understood. However, I have not had any issues like that with my code. 

Sorry if I can’t help much but I am not working anymore on this since September.

Regards,
Neri

**Comment by Cladett** [comment]
> Hi @nndei, I've created the Handle collision as you suggested. However it seems that the V-REP opening with the handle of a collision object requires so many times and causes the failure of connection when I try to start the training (or when I perform the check before the training using external script).
> Do you think that these events are caused by the usage of a non-pure shapes as obstacles in the V-REP scene?
> 
> Thank you.
> Best Regards, Andrea.

**Comment by Cladett** [comment]
Dear @poliandre98, are you still working on this dVRL repo? I would be interested to know more about what you are working right now. 
Thank you
Cheers

**Comment by poliandre98** [comment]
> Dear @poliandre98, are you still working on this dVRL repo? I would be interested to know more about what you are working right now.
> Thank you
> Cheers

Dear @Cladett, I have just finished my work focused on avoiding obstacles in a simulated environment of tumor removal using da Vinci tools. Although the task of avoiding obstacles is accomplished, it's still a very simple scene with many possibilities to make improvements

**Comment by nndei** [comment]
Dear @poliandre98, I’d be interested to know in which lab you are doing this research. If you may contact me on my email, written at the end of the guide.txt file in this repo, it’d be nice to talk about it. I am currently looking for a spot. 
Regards
